/**
 * SEO helpers — one place for the public URL, per-page metadata and the
 * structured-data builders, so canonical, Open Graph and schema never drift.
 */
import type { Metadata } from "next";
import { brand } from "@/data/site";

/**
 * Public origin, without a trailing slash.
 *
 * Netlify serves the apex domain as primary and 301-redirects www to it, so
 * the apex is the canonical host. Canonicals, the sitemap and robots.txt must
 * all use this exact origin, or every URL Google is given is a redirect.
 */
export const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL || "https://squarebirdnet.com").replace(/\/+$/, "");

export const SITE_NAME = "SQUARE — Bird Net & Invisible Grill";

/** Stable schema.org identifier for the business, referenced from every page. */
export const BUSINESS_ID = `${SITE_URL}/#business`;

/** Robots directives for pages that should appear in search. */
export const INDEX_ROBOTS: Metadata["robots"] = {
  index: true,
  follow: true,
  "max-image-preview": "large",
};

/**
 * 1200x630 share cards generated by `node scripts/build-media.mjs social`.
 * The key is the file name under /images/social/.
 */
export const SOCIAL_IMAGES = {
  home: "Balcony protected by an invisible grill overlooking the city",
  about: "A SQUARE installer at a balcony fitted with bird netting",
  services: "Residential towers with protected balconies",
  projects: "Apartment building with bird netting fitted across its balconies",
  videos: "Large-span bird netting installed inside a factory shed",
  "bird-netting": "Bird netting installed across apartment balconies",
  "invisible-grill": "Stainless steel invisible grill on a high-rise balcony",
  "bird-spikes": "Bird spikes installed along a rooftop parapet",
  "cricket-net": "Cricket box net with artificial turf pitch",
} as const;

export type SocialImage = keyof typeof SOCIAL_IMAGES;

export function socialImage(key: SocialImage) {
  return { url: `/images/social/${key}.jpg`, width: 1200, height: 630, alt: SOCIAL_IMAGES[key], type: "image/jpeg" };
}

export function absoluteUrl(path = "/") {
  return path === "/" ? `${SITE_URL}/` : `${SITE_URL}${path}`;
}

type PageMetaInput = {
  /** Page title without the " | SQUARE" suffix (the layout template adds it). */
  title: string;
  description: string;
  /** Route path, e.g. "/services/bird-netting". */
  path: string;
  image?: SocialImage;
  /** Keeps the page out of search results while still letting crawlers follow its links. */
  noIndex?: boolean;
  /** Use the title as-is, without the layout's " | SQUARE" template. */
  absoluteTitle?: boolean;
};

/** Canonical, Open Graph, Twitter and robots metadata for one page. */
export function pageMetadata({ title, description, path, image = "home", noIndex, absoluteTitle }: PageMetaInput): Metadata {
  const card = socialImage(image);
  const socialTitle = absoluteTitle ? title : `${title} | ${brand.name}`;

  return {
    title: absoluteTitle ? { absolute: title } : title,
    description,
    // A noindex page must not point Google at a canonical.
    alternates: noIndex ? undefined : { canonical: absoluteUrl(path) },
    openGraph: {
      type: "website",
      locale: "en_IN",
      siteName: SITE_NAME,
      url: absoluteUrl(path),
      title: socialTitle,
      description,
      images: [card],
    },
    twitter: {
      card: "summary_large_image",
      title: socialTitle,
      description,
      images: [{ url: card.url, alt: card.alt }],
    },
    robots: noIndex ? { index: false, follow: true } : INDEX_ROBOTS,
  };
}

/** BreadcrumbList schema. `trail` excludes Home, which is always first. */
export function breadcrumbSchema(trail: { name: string; path: string }[]) {
  const items = [{ name: "Home", path: "/" }, ...trail];
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: item.name,
      item: absoluteUrl(item.path),
    })),
  };
}
